/*
 * This source file was generated by the Gradle 'init' task
 */
package org.lousing;

import org.lousing.foundation.EnhancedFor;
import org.lousing.leetcode.ContainsDuplicate;
import org.lousing.leetcode.ContainsDuplicateV2;
import org.lousing.leetcode.TwoSum;

import java.util.ArrayList;
import java.util.List;

public class App {
  public String getGreeting() {
    return "Hello World!";
  }

  public static void main(String[] args) {
    ContainsDuplicateV2.showDemo();
  }
}
