/*
 * This source file was generated by the Gradle 'init' task
 */
package org.lousing;

import org.lousing.leetcode.ContainsDuplicateV2;

public class App {
  public String getGreeting() {
    return "Hello World!";
  }

  public static void main(String[] args) {
    ContainsDuplicateV2.showDemo();
  }
}
