/*
 * This source file was generated by the Gradle 'init' task
 */
package org.lousing;

import java.util.ArrayList;
import java.util.List;

public class App {
  public String getGreeting() {
    return "Hello World!";
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());
    System.out.println("Awesome 1");
    List<String> fruitList = new ArrayList<>();
    fruitList.add("apple");
    fruitList.add("banana");

    for (String fruit : fruitList) {
     System.out.println(fruit);
    }
  }
}
