/*
 * This source file was generated by the Gradle 'init' task
 */
package lousing;

import org.junit.jupiter.api.Test;
import org.lousing.App;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
  @Test
  void shouldHaveAppNameAsPracticeJava() {
    assertEquals("Practice Java", App.appName);
  }
}
